### ISSUE TITLE
Need to figure out what files can safely come out of version control

### ISSUE THREAD

**Issue by adambatson** [adambatson/gbtis#13]
The repo has become cluttered with a bunch of files that we **think** may or may not be necessary.  I just pulled master into one of my dev branches and it caused 6 merged conflicts.  A lot of these where on some auto-generated visual studio files.  We should try to figure out which files for sure can go in order to avoid future merge conflict headaches.

**Comment by rscarson** [comment]
A lot of it is architecture and project settings changes.

This problem should disappear once we exit this initial stage of development
