### ISSUE TITLE
'Start input' starts the standby window

### ISSUE THREAD

**Issue by rscarson** [adambatson/gbtis#31]

**Comment by MeloDeMelo** [comment]
as opposed to?

**Comment by rscarson** [comment]
The input window? That's why it's called start input

If input starts standby, what does start standby do?

**Comment by MeloDeMelo** [comment]
why would the admin window need that? all you have to do is wave to get it there

**Comment by rscarson** [comment]
I don't have the kinect, dude

**Comment by rscarson** [comment]
That's why there's a button

**Comment by MeloDeMelo** [comment]
i was very confused when i first programmed that i will have to say

**Comment by MeloDeMelo** [comment]
ok its a 2 sec change one min
