### ISSUE TITLE
Reflective light possibly messing with sensor

### ISSUE THREAD

**Issue by adambatson** [adambatson/gbtis#42]
Prof Rajan was having some trouble using this when he was wearing his bright orange hoodie, seemed better once he took it off.  Not sure if there's much we can do to fix this but it's worth looking into.

**Comment by rscarson** [comment]
If we could measure the input jitter, we could use that to set the smoothing dynamically in the kinect wrapper

**Comment by rscarson** [comment]
What if in getAverageFingerTipPosition() we get the distance between the averaged point and the given point, then adjust the smoothing factor based on it

So more shaky input would be smoothed more, and smoother input would be more responsive
