### ISSUE TITLE
kinect wrapper boolean property to determine tracking status

### ISSUE THREAD

**Issue by rscarson** [adambatson/gbtis#58]
In canvas / admin window I could use the information

**Comment by adambatson** [comment]
You mean like whether or not someone is being tracked?

**Comment by rscarson** [comment]
Yeah, so on standby would be false
On canvas true if we're tracking a body

**Comment by rscarson** [comment]
So I can display a pip on the tracked body's hand on admin and show status info
And to hide the cursor on tracking errors in canvas

**Comment by adambatson** [comment]
So you want just a boolean or do you also want to know which body is the active body as well?

**Comment by rscarson** [comment]
The location is already available as FingerPositionChanged

**Comment by rscarson** [comment]
The body ID is useless to me
